FROM docker:cli as docker-cli

FROM jenkins/jenkins:lts
USER root

# Install Node.js 20 (LTS) directly into Jenkins
RUN apt-get update && \
    apt-get install -y curl && \
    curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
    apt-get install -y nodejs && \
    npm install -g npm@latest

# Copy docker CLI 
COPY --from=docker-cli /usr/local/bin/docker /usr/local/bin/docker

USER root
