services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
      # Keep network: host during build to ensure Node.js installs successfully
      network: host

    user: root

    ports:
      # Return to the port you are familiar with
      - "8081:8080"
      - "50000:50000"

    volumes:
      - jenkins_data:/var/jenkins_home
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock

    environment:
      - TZ=Asia/Kolkata

    dns:
      - 8.8.8.8
      - 8.8.4.4
    extra_hosts:
      - "github.com:20.207.73.82"

volumes:
  jenkins_data:

# run this for jenkins
# docker compose -f docker-compose.jenkins.yml up -d
# docker compose -f docker-compose.jenkins.yml down

# jenkins link
# http://localhost:8081