-- Add Face Descriptor column for client-side face recognition
ALTER TABLE workers 
ADD COLUMN IF NOT EXISTS face_descriptor jsonb;

-- Comment: This column will store the array of numbers (128 floats) generated by face-api.js
